'use strict';

module.exports = {
  async up (queryInterface, Sequelize) {
    await queryInterface.bulkInsert('Cards', [
      {
        title: "Лук",
        about: "Очень сладкий и сочный лук!",
        price:"100",
        category_id:"1",
        image:'http://localhost:3001/images/img/onion.jpeg',
        user_id:"1",
        contacts: "88005553535",
        location:"Россия, Краснодарский край, г.Анапа, ул.Пушкина, д.Колотушкина",
        quantity_id: "1",
        quantity: "20",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Помидорки",
        about: "Очень сладкий и сочный помидор!",
        price:"100",
        category_id:"1",
        image:'http://localhost:3001/images/img/tomato.jpeg',
        user_id:"1",
        contacts: "88005553535",
        location:"Россия, Краснодарский край, г.Анапа, ул.Пушкина, д.Колотушкина",
        quantity_id: "1",
        quantity: "20",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Камаз",
        about: "Очень сладкий и сочный камаз!",
        price:"100",
        category_id:"4",
        image:'http://localhost:3001/images/img/kamaz.jpeg',
        user_id:"1",
        contacts: "88005553535",
        location:"Россия, Краснодарский край, г.Анапа, ул.Пушкина, д.Колотушкина",
        quantity_id: "1",
        quantity: "20",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Трактор",
        about: "Очень быстрая и резкая машина",
        price:"110000",
        category_id:"4",
        image:'http://localhost:3001/images/img/tractor.jpeg',
        user_id:"2",
        contacts: "88006661369",
        location:"Россия, Москва, Красная Площадь",
        quantity_id: "2",
        quantity: "420",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Сыр с дырочками",
        about: "Очень сладкий и сливочный!!!",
        price:"110000",
        category_id:"6",
        image:'http://localhost:3001/images/img/cheeze.jpeg',
        user_id:"2",
        contacts: "88006661369",
        location:"Россия, Москва, Красная Площадь",
        quantity_id: "2",
        quantity: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Довезу что угодно ",
        about: "прямо ВСЁ довезу реально",
        price:"110000",
        category_id:"13",
        image:'http://localhost:3001/images/img/trail.jpeg',
        user_id:"2",
        contacts: "88006661369",
        location:"Россия, Москва, Красная Площадь",
        quantity_id: "3",
        quantity: "1",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Винишко домашнее",
        about: "Почти Гевюрцтраминер...",
        price:"110000",
        category_id:"8",
        image:'http://localhost:3001/images/img/wine.jpeg',
        user_id:"2",
        contacts: "88006661369",
        location:"Россия, Москва, Красная Площадь",
        quantity_id: "3",
        quantity: "4",
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Засеять поле",
        about: "Засеиваю поле со скоростью звука",
        price:"8000000",
        category_id:"14",
        image:'http://localhost:3001/images/img/seed.jpeg',
        user_id:"3",
        contacts: "88005552222",
        location:"Россия, г.Челябинск, ул. Четкая, д.777",
        quantity_id: "2",
        quantity: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        title: "Вспахать",
        about: "Пашу со скоростью звука",
        price:"8000000",
        category_id:"14",
        image:'http://localhost:3001/images/img/unseed.jpeg',
        user_id:"3",
        contacts: "88005552222",
        location:"Россия, г.Челябинск, ул. Четкая, д.777",
        quantity_id: "2",
        quantity: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down (queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
  }
};
